---
title: "buoy_A01_ERDDAP"
author: "Aaron Shavitz"
format: 
  html:
    code-fold: true
    code-summary: "Show the code"
---
[Return to Home Page (Index)](https://ashavitz.github.io/wellfleet_project/)

# A01 Buoy ERDDAP Data - Massachusetts Bay

```{r, echo=FALSE}
# Using knitr package to read code chunks from buoy_A01_ERDDAP.R

# Set the root directory to the current folder
knitr::opts_knit$set(root.dir = here::here())

# Read in the R script from the 'scripts' folder (relative to the root project directory)
knitr::read_chunk("../scripts/buoy_A01_ERDDAP.R")
```

```{r Header}
#| code-fold: false
```

```{r Custom Functions, echo=FALSE, message=FALSE, warning=FALSE}
```

### Load Libraries
```{r Load Libraries, message=FALSE, warning=FALSE}
```

### Set Global ggplot Themes
```{r Set Global ggplot Themes, message=FALSE, warning=FALSE}
```

### A01 CTD - CTD Temperature and Salinity @ 1m and 20m depths
```{r A01 CTD 2001 - 2025, message=FALSE, warning=FALSE}
```

### A01 Aanderaa - Historic Surface Currents
```{r A01 Aanderaa - Realtime Surface Currents and O2, message=FALSE, warning=FALSE}
```

### A01 Met - Meteorology
```{r A01_met_all, message=FALSE, warning=FALSE}
```
