---
title: "buoy_221_ERDDAP"
author: "Aaron Shavitz"
format: 
  html:
    code-fold: true
    code-summary: "Show the code"
---
[Return to Home Page (Index)](https://ashavitz.github.io/wellfleet_project/)

# 221 Buoy ERDDAP Data (Cape Cod Bay)

```{r, echo=FALSE}
# Using knitr package to read code chunks from buoy_221_ERDDAP.R

# Set the root directory to the current folder
knitr::opts_knit$set(root.dir = here::here())

# Read in the R script from the 'scripts' folder (relative to the root project directory)
knitr::read_chunk("../scripts/buoy_221_ERDDAP.R")
```

```{r Header}
#| code-fold: false
```

### Importing Files via ERDDAP
```{r Importing files via ERDDAP, message=FALSE, warning=FALSE}
```

### Load Libraries
```{r Load Libraries, message=FALSE, warning=FALSE}
```

### Set Global ggplot Themes
```{r Set Global ggplot Themes, message=FALSE, warning=FALSE}
```

### Air Temperature Measurements
```{r Air temperature measurements, message=FALSE, warning=FALSE}
```

### SST Measurements
```{r Sea surface temperature (SST) measurements, message=FALSE, warning=FALSE}
```

### Surface Current (acm) measurements
```{r Surface Current (acm) measurements, message=FALSE, warning=FALSE}
```

### Wave measurements
```{r Wave measurements, message=FALSE, warning=FALSE}
```

### Create data set for analysis
```{r Create data set for analysis, message=FALSE, warning=FALSE}
```

### Plot all Variables
```{r Plot all Variables, message=FALSE, warning=FALSE}
```
