---
title: "buoys_merged"
author: "Aaron Shavitz"
format: 
  html:
    code-fold: true
    code-summary: "Show the code"
    fig-format: png
    fig-dpi: 300
    
execute:
  dev: ragg_png
  fig-width: 6.5
  fig-height: 4
---
[Return to Home Page (Index)](https://ashavitz.github.io/wellfleet_project/)
 
# Massachusetts Bay, Boston Harbor, and Cape Cod Bay Buoys

```{r, echo=FALSE}
# Using knitr package to read code chunks from buoys_merged.R

# Set the root directory to the current folder
knitr::opts_knit$set(root.dir = here::here())

# Read in the R script from the 'scripts' folder (relative to the root project directory)
knitr::read_chunk("../scripts/buoys_merged.R")
```

```{r Header}
#| code-fold: false
```

### Load Libraries
```{r Load Libraries, message=FALSE, warning=FALSE}
```

### Load Buoy Data
```{r Load Buoy Data, message=FALSE, warning=FALSE}
```

### Set Global ggplot Themes and Plotting Objects
```{r Set Global ggplot Themes and Plotting Objects, message=FALSE, warning=FALSE}
```

### Visualize Buoy Data
```{r Visualize Buoy Data, message=FALSE, warning=FALSE}
```

### Plots for Final Report
```{r Plots for Final Report, message=FALSE, warning=FALSE, fig.width=13, fig.height=4}
```