---
title: "ccs_stations"
author: "Aaron Shavitz"
format: html
---
[Return to Home Page (Index)](https://ashavitz.github.io/wellfleet_project/)

# CCS Water Quality Data - Wellfleet

```{r, echo=FALSE}
# Using knitr package to read code chunks from ccs_stations.R

# Set the root directory to the current folder
knitr::opts_knit$set(root.dir = here::here())

# Read in the R script from the 'scripts' folder (relative to the root project directory)
knitr::read_chunk("../scripts/ccs_stations.R")
```

```{r Header}
```

### Load Libraries
```{r Load Libraries, message=FALSE, warning=FALSE}
```

### Read CCS csv data
```{r csv import from CCS, message=FALSE, warning=FALSE}
```

### Filter Only "Full" Years With Exactly One Monthly Measurement
```{r Filter Only "Full" Years With Exactly One Monthly Measurement}
```

### Filter Only "Full" Summers With Exactly One Monthly Measurement (June - September)
```{r Filter Only "Full" Summers With Exactly One Monthly Measurement June - September}
```

### Set Global ggplot Themes
```{r Set Global ggplot Themes, message=FALSE, warning=FALSE}
```

### Plot All Data Over Time (~Monthly, Annual Mean, Annual Median)
```{r Plot All Data Over Time, message=FALSE, warning=FALSE}
```
